apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fireflyiii
labels:
  - pairs:
      app.kubernetes.io/name: fireflyiii
      app.kubernetes.io/component: budget-management
      app.kubernetes.io/part-of: user-apps
      app.kubernetes.io/managed-by: argocd
    
resources:
  - namespace.yaml
  - fireflyiii-secrets-sealed.yaml
  - core/
  - cron/
  - importer/
  - ../../../common/cilium-network-policies/
