apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-stack

labels:
  - pairs:
      app.kubernetes.io/name: prometheus-stack
      app.kubernetes.io/component: prometheus-monitoring
      app.kubernetes.io/part-of: monitoring
      app.kubernetes.io/managed-by: argocd
    

resources:
  - namespace.yaml
  - alerts/
  - dashboards/
  # - datasources/
  - http-routes/
  - monitors/
  - secrets/

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 77.12.0
    releaseName: kube-prometheus-stack
    namespace: prometheus-stack
    valuesFile: values.yaml
    includeCRDs: true