apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-stack    

resources:
  - namespace.yaml
  - alerts/
  - cilium-netpols/
  - dashboards/
  # - datasources/
  - http-routes/
  - monitors/
  - secrets/
  - ../../common/cilium-network-policies/

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 80.14.4
    releaseName: kube-prometheus-stack
    namespace: prometheus-stack
    valuesFile: values.yaml
    includeCRDs: true