apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karakeep
labels:
  - pairs:
      app.kubernetes.io/name: karakeep
      app.kubernetes.io/managed-by: argocd
    includeSelectors: true

resources:
  - namespace.yaml
  - karakeep-secret-sealed.yaml
  - chrome/
  - meilisearch/
  - karakeep-web/