apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karakeep
labels:
  - pairs:
      app.kubernetes.io/name: karakeep
      app.kubernetes.io/component: bookmarks
      app.kubernetes.io/part-of: user-apps
      app.kubernetes.io/managed-by: argocd
    

resources:
  - namespace.yaml
  - karakeep-secret-sealed.yaml
  - chrome/
  - meilisearch/
  - karakeep-web/
  - ../../../common/cilium-network-policies/