apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fireflyiii
    
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - pvc.yaml
  - cilium-netpol.yaml

configMapGenerator:
  - name: fireflyiii-other-configs
    files:
      - config/other_configs.env