apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
labels:
  - pairs:
      app.kubernetes.io/name: homepage
      app.kubernetes.io/component: dashboard
      app.kubernetes.io/part-of: user-apps
      app.kubernetes.io/managed-by: argocd
    
resources:
  - namespace.yaml
  - deployment.yaml
  - homepage-vars-secret-sealed.yaml
  - http-route.yaml
  - rbac.yaml
  - service.yaml
  - cilium-netpol.yaml
  - ../../../common/cilium-network-policies/

configMapGenerator:
  - name: homepage-config
    files:
      - config/bookmarks.yaml
      - config/custom.css
      - config/custom.js
      - config/docker.yaml
      - config/kubernetes.yaml
      - config/proxmox.yaml
      - config/services.yaml
      - config/settings.yaml
      - config/widgets.yaml
