apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway

labels:
  - pairs:
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: argocd
    

resources:
  - namespace.yaml
  - gateway-internal.yaml
  - gateway-external.yaml
  - http-redirect-internal.yaml