apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"

resources:
  - class.yaml
  - namespace.yaml
  - gateway-internal.yaml
  - gateway-external.yaml
  - http-redirect-internal.yaml