apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fireflyiii

labels:
  - pairs:
      # Added for Cilium network policies
      netpol.cilium.io/egress-to-intra: "true"
      netpol.cilium.io/egress-to-kube-dns: "true"
      netpol.cilium.io/ingress-deny: "true"
    
resources:
  - cronjob.yaml