---
# - Miscellaneous:

# - Media:

- Network Services:
    - Cloudflared:
        icon: https://cdn-1.webcatalog.io/catalog/cloudflare-zero-trust/cloudflare-zero-trust-icon-unplated.png?v=1714773945620
        href: https://dash.cloudflare.com/
        description: External Access
        siteMonitor: http://cloudflared-metrics.cloudflared.svc.cluster.local:2000/ready
    - Pihole:
        icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
        href: http://pihole.{{HOMEPAGE_VAR_BASE_DOMAIN}}
        description: Main DNS Server
        siteMonitor: http://pihole
    - Tailscale:
        icon: https://play-lh.googleusercontent.com/wczDL05-AOb39FcL58L32h6j_TrzzGTXDLlOrOmJ-aNsnoGsT1Gkk2vU4qyTb7tGxRw
        href: https://login.tailscale.com/admin/machines/
        description: Exit Node Machine

# - Monitoring:

# - Management:

- Infrastructure:
    - Plusle:
        icon: https://img.icons8.com/fluency/2x/proxmox.png
        href: https://plusle.{{HOMEPAGE_VAR_BASE_DOMAIN}}
        ping: plusle
        description: GMKTEC NucBox M5 PLUS
        widget:
          type: proxmox
          url: https://plusle:8006
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_PWD}}"
          #node: pve-1  # Uncomment if proxmox has more than 1 node