apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: excalidraw
labels:
  - pairs:
      app.kubernetes.io/name: excalidraw
      app.kubernetes.io/component: whiteboard
      app.kubernetes.io/part-of: user-apps
      app.kubernetes.io/managed-by: argocd
    

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - http-route.yaml