apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

labels:
  - pairs:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: cert-manager-controller
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: argocd
    

resources:
  - namespace.yaml
  - cloudflare-token-secret-sealed.yaml
  - cluster-issuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.19.1
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml
    includeCRDs: true
