apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-server

labels:
  - pairs:
      app.kubernetes.io/name: metrics-server
      app.kubernetes.io/component: metrics-server-controller
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: argocd
    

resources:
  - namespace.yaml
  - ../../../common/cilium-network-policies/

helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.13.0
    namespace: metrics-server
    valuesFile: values.yaml