apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudnative-pg-operator
  labels:
    app.kubernetes.io/name: cloudnative-pg
    release: kube-prometheus-stack
    prometheus: kube-prometheus-stack-prometheus
spec:
  namespaceSelector:
    matchNames:
      - cloudnative-pg
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: cloudnative-pg-operator
      app.kubernetes.io/name: cloudnative-pg