apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: memos
    cnpg.io/cluster: memos-database
    release: kube-prometheus-stack
    prometheus: kube-prometheus-stack-prometheus
  name: memos-database
spec:
  namespaceSelector:
    matchNames:
      - cloudnative-pg
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: memos-database