apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: changedetection
labels:
  - pairs:
      app.kubernetes.io/name: changedetection
      app.kubernetes.io/component: monitorwebsites
      app.kubernetes.io/part-of: user-apps
      app.kubernetes.io/managed-by: argocd

resources:
  - namespace.yaml
  - changedetection/
  # - selenium/
  - playwright/