apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"

resources:
  - namespace.yaml
  - barman-plugin/
  - cloudnative-pg-operator/