apiVersion: v1
kind: Service
metadata:
  name: chrome
  labels:
    app: karakeep
    tier: chrome
spec:
  selector:
    app: karakeep
    tier: chrome
  ports:
    - name: chrome-svc
      port: 9222
      protocol: TCP
      targetPort: chrome-pod
  type: ClusterIP