apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pairdrop
labels:
  - pairs:
      app.kubernetes.io/name: pairdrop
      app.kubernetes.io/component: file-sharing
      app.kubernetes.io/part-of: user-apps
      app.kubernetes.io/managed-by: argocd
    
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - ../../../common/cilium-network-policies/