apiVersion: v1
kind: Service
metadata:
  name: karakeep-web
spec:
  selector:
    app: karakeep
    tier: web
  ports:
    - name: karakeep-svc
      port: 3000
      protocol: TCP
      targetPort: karakeep-pod
  type: ClusterIP