---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-secrets
spec:
  encryptedData:
    grafana-admin-password: AgDR2NkZ/lDXuvE708E3gJHc12D9yPwehsamLciEdwQAScIZ8VjMsVukkgvkPSPtZs5q+Qf3XUAzpNIZEZPLt1jDaEg/n1NkMXEIZMHE7hRrYJ2sJ4/pVi4xpm56l0q4RjNEX80wMQeYAUbepL8QNPwd2x1Ne2ndN82iD0niyqHUOkXqQs/LAO9ZMwwrHozEOA14fRC7EbhfknSMtNaeM9RMeUWsIV4pDH/phalA/gfhQdERuWy1tZa5N/Cp2wMcFyB2cfzl6ClKdTvKzH2hM9+9SqMAdudklRv1Q+Ckkyk1Qzq4Cyw+43niNgREtaZAKBGmra8J/z/0mE6TAU5yZzZfllPyJ/HnOzE+58FC7bZH+m2EpZj/UI9ibe1N3VjiX/mFuaxfrHv+1auzyrwTSN2kdbR96GlHFT7WCf3Sp0yp/89U0KBQWjpREsFZgWg+6hB4VGfYu0zAGcqSWP6VM34wNL4df0Je6TzKo5OAWoMaJdN5U2dGoEdFsAQB8JKtdava9y7AaYjDuPHVleoHyX0RYOtw+y37dxQr10S2tW2f2gpJGZRKD/jz24caF/r+F3M3WlmbbKUJEi56Jc5V2QNYrAjYJN6TRyALum9r0YKE2SiZ0cJgThoROKLVv7lBrTeW84TQbvKGF+Vdax/oZ2byO0hrxdQs508vTUzzxlcJU0fG4pBKOxEq+h1Eb4spNO00EDYv9fyiLlZYkAMG/Ckf+0JescQDH9Il5AM11mBJRw==
    grafana-admin-user: AgBjK9oQq61BhEs69I2PbYkMfOOVGTe3lJ52qoRNM51F7ukzz/fx5tr/kzNTKy7/oAsnjVXu67ukaui/KS4nW5SLqDFm/Q1xm67lc74ilcBdccwwbgIhbSlAygk2DFJ/PI2adfanmERWyGYAVHu0byM6Ut0OgWWQJ/VztVuokcMTXIc2Ex13Q0E8Eo8K3RVn6rgyErK5gYAsZTtjUOZUiOdF5xsmH3ZFTAY0E6hwSAp9RKuW319m3ZRKAv8GwNq6lj3KwoeMC4CVO8YHWIW5CmtiL0qCRuZHKHr4E9lzXaxD8vyqWVSBPic3FShpmRrYIRD7z1Zub1CPBOd9O78GVUXPzedME//galnDYjZIcp2MpQeB0OmFbqNvL1uLyB1LE1PRCAlAtOiBaNd14+Du8wNUqQpGysaLx7dsROCMY2q9qWvkRoIDO7bU84gkRYJ1kKzlV8zAQMGefx9iqftbeF9FRlTaBeG6Rig2nC2iRVQebBaS/dF+3yERjMcpD17/+khVETSX++Zz1jMIjcKqMwrN4O1nF1nVWGkMY1+vQhMQb4QBgFAZmi0do/r/9CWIoF90cOnC/ZbvwURaHROzH82HSPSkWOyaOK2at5e1BE4caiqNGYPjCerAcplEGsIsdQ0yRs5DgmhaCil/clqkXnKClNCiJUBZSzKCInKQM+ccSAMIV/rO5ShR/+a3ljuwicgd7eO7hg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-secrets
    type: Opaque
