apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio
  labels:
    app: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stremio
  template:
    metadata:
      labels:
        app: stremio
        netpol.cilium.io/egress-to-kube-dns: "true"
        netpol.cilium.io/egress-to-world: "true"
        netpol.cilium.io/egress-to-intra: "true"
        netpol.cilium.io/ingress-from-ingress: "true"
    spec:
      containers:
        - name: stremio
          image: tsaridas/stremio-docker:v1.2.10
          ports:
            - containerPort: 8080
          env:
            - name: NO_CORS
              value: "1"
            - name: AUTO_SERVER_URL
              value: "1"
            - name: APP_PATH
              value: "/srv/stremio-config"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - name: stremio-data
              mountPath: /srv/stremio-config
      volumes:
        - name: stremio-data
          persistentVolumeClaim:
            claimName: stremio-pvc
