apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stremio
labels:
  - pairs:
      app.kubernetes.io/name: stremio
      app.kubernetes.io/component: media
      app.kubernetes.io/part-of: user-apps
      app.kubernetes.io/managed-by: argocd
    

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - http-route.yaml
  - http-route-external.yaml
  - pvc-data.yaml