apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nodecast-tv
labels:
  - pairs:
      app.kubernetes.io/name: nodecast-tv
      app.kubernetes.io/component: iptv
      app.kubernetes.io/part-of: user-apps
      app.kubernetes.io/managed-by: argocd
    
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - http-route-external.yaml
  - ../../../common/cilium-network-policies/