apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memos
labels:
  - pairs:
      app.kubernetes.io/name: memos
      app.kubernetes.io/managed-by: argocd
    includeSelectors: true

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - pvc.yaml
  - configmap.yaml