apiVersion: v1
kind: Service
metadata:
  name: memos-svc   # Service Name can't be "memos"  
spec:
  selector:
    app: memos
  ports:
    - name: grpc-port
      port: 10001
      targetPort: memos-pod
      protocol: TCP
      appProtocol: kubernetes.io/h2c
    - name: http-port
      port: 10002
      targetPort: memos-pod
      protocol: TCP
