apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared

labels:
  - pairs:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/component: external-access
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: argocd
    

configMapGenerator:
  - name: config
    namespace: cloudflared
    files:
      - config.yaml

resources:
  - namespace.yaml
  - cloudflared-tunnel-creds-secret-sealed.yaml
  - deployment.yaml
  - service.yaml
  - cilium-netpol.yaml
  - ../../../common/cilium-network-policies/