apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
spec:
  selector:
    app: cloudflared
  ports:
    - name: liveness
      port: 2000       # service port
      targetPort: 2000 # container port
      protocol: TCP
