apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
labels:
  - pairs:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/component: password-management
      app.kubernetes.io/part-of: user-apps
      app.kubernetes.io/managed-by: argocd
    

resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
  - http-route.yaml
  - ../../../common/cilium-network-policies/