apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg

resources:
  # - cluster-init.yaml               # Only for initial cluster creation, after first backup use cluster-from-backup.yaml
  - cluster-from-backup.yaml
  - fireflyiii-db-secret-sealed.yaml
  - scheduled-backup.yaml
  - db-netpol.yaml