apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aplications-alerts.yaml
  - argocd-alerts.yaml
  - kubernetes-alerts.yaml
  - prometheus-stack-alerts.yaml
  - storage-alerts.yaml
  - storage-backup-alerts.yaml