apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goti-stack

labels:
  - pairs:
      app.kubernetes.io/name: goti-stack
      app.kubernetes.io/component: push-notifications
      app.kubernetes.io/part-of: monitoring
      app.kubernetes.io/managed-by: argocd
    
resources:
  - namespace.yaml
  - goti-stack-config-secrets-sealed.yaml
  - gotify/
  - gotigram/
  - ../../common/cilium-network-policies/